@startuml 多重タブ
[*] --> 作戦A : 初期状態

state 作戦A {
  [*] --> 概要
  概要 --> グラフ : 子タブ選択
  グラフ --> コメント
  コメント --> 概要
}

作戦A --> 作戦B : 親タブ切替

state 作戦B {
  [*] --> グラフ
  グラフ --> コメント : 子タブ切替
  コメント --> 概要
}
@enduml
